# R-y-PYTHON
---
title: "R-y-PYTHON"
author: "RUBER HERNANDEZ"
date: "10/12/2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RETICULE LIBRERIA EN PYTHON


```{r NOTA, message=TRUE, results='markup'}
library(reticulate)
os <- import("os")
os$listdir(".")
```

```{r}
source_python("add.py")
add(2,4)
```


```{r}
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4))
sum <- x$cumsum() 
print(sum) # objeto de salida en python

py_to_r(sum) # objeto de salida en R
```

## AYUDA POR COMANDO

```{r}
help(py_to_r)
py_help(os$chdir)
```

## array

```{r}
a <- np_array(c(1:10), dtype = "float16")
a
b <- np_array(c(1:10), order =  "C")
b
```

```{r}
datos <- iris
head(datos)
datos_py = r_to_py(datos) # pasar los datos de R a python
```


## escribir directamente en PYTHON

```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```


## Sparse Matrix

```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat = sparseMatrix(
  i = sample(N, N, replace = F), 
  j = sample(N, N, replace = F), 
  x = runif(N),
  dims = c(N,N)
) 
sparse_mat
sparse_mat_py = r_to_py(sparse_mat) # pasar los datos de R a python
```

```{python}
r.sparse_mat_py # resultado en python
```
```{r}
py_to_r(sparse_mat_py)
```

