---
title: "Distribución Hipergeométrica"
author: "Curso de Estadística Descriptiva"
date: "7/2/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Distribución Hipergeométrica

Supongamos que tenemos 20 animales, de los cuales 7 son perros. Queremos medir la probabilidad de encontrar un número determinado de perros si elegimos $k=12$ animales al azar. 

# En `R`

```{r}
library(Rlab)
M = 7
N = 13
k = 12
dhyper(x = 0:12, m = M, n = N, k = k) # probabilidad de sacar perros en cada intento
phyper(q = 0:12, m = M, n = N, k = k) # funcion de distribucion acumulada
qhyper(p = 0.5, m = M, n = N, k = k)# Los cuartiles
rhyper(nn = 1000, m = M, n = N, k = k) -> data # numero de perros de esas extracuiones
hist(data, breaks = 8)
```


## En `Python`
```{python}
from scipy.stats import hypergeom
import matplotlib.pyplot as plt
import numpy as np

  [M, n, N] = [20, 7, 6]
  rv = hypergeom(M, n, N)
  x = np.arange(0, n+1)
  y = rv.pmf(x)

  mean, var, skew, kurt = rv.stats(moments = 'mvsk')
  print("Media %f"%mean)
  print("Varianza %f"%var)
  print("Sesgo %f"%skew)
  print("Curtosis %f"%kurt)

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x, y, 'bo' )
ax.vlines(x,0,y, lw = 2, alpha = 0.5)
ax.set_xlabel("Número de perros entre los 12 elegidos al azar")
ax.set_ylabel("Distribución de probabilidad de H(13,7,12)")
plt.show()
```

